### ISSUE TITLE
Android work

### ISSUE THREAD

**Issue by appt2** [caoccao/swc4j#2]
Is it supported on Android?

**Comment by appt2** [comment]
> It's not my top priority for now. I encourage you to submit pull request if you could get it done as it's half way done.

I am very interested to port for android but I am not so professional in java I want this project for ghost web thank you please port for android also you create amazing codes

**Comment by caoccao** [comment]
That will take some time.

**Comment by appt2** [comment]
> That will take some time.

Anyway, thank you for porting it for Android too, because I tested it in a separate project and got an error

**Comment by appt2** [comment]
Please port a specific model for Android, for example, let's give the code so that the output is in the form of a file, because actually the output of TypeScript is a JavaScript file.

**Comment by caoccao** [comment]
The android snapshot build is at the actions. Please take a try.
