### ISSUE TITLE
【Help】Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead

### ISSUE THREAD

**Issue by fanksy** [caoccao/swc4j#3]
```Java
Swc4jTranspileOptions options = new Swc4jTranspileOptions()
                .setCaptureAst(true)
                .setUseTsDecorators(true)
                .setUseDecoratorsProposal(true)
                .setEmitMetadata(false)
                .setMediaType(getMediaType(path));
```
请问该如何设置才能正常解析

有一个相关的issue：https://github.com/babel/babel-eslint/issues/662

解决方式：
```json
"parserOptions": {
    "ecmaFeatures": {
      "legacyDecotators": true
    }
  }
```
这个在Options里面没有对应的选项

**Comment by caoccao** [comment]
Please leave the complete code so that it can be reproduced.

**Comment by caoccao** [comment]
I fail to see there's anything wrong. Please check this [commit](https://github.com/caoccao/swc4j/commit/a91f6f0a8cb12a5ce1ebcaf723a5eb9328abddb5) out.

**Comment by fanksy** [comment]
> I fail to see there's anything wrong. Please check this [commit](https://github.com/caoccao/swc4j/commit/a91f6f0a8cb12a5ce1ebcaf723a5eb9328abddb5) out.

```JavaScript
import React from 'react';
import { connect } from 'react-redux';

const ConditionModal = loadable(() => import('components/ConditionModal'));

@connect((state) => {

  return {
  };
})
export default class MyComponent extends React.Component {
  componentDidMount() {}

  render() {
    const {
      visible,
    } = this.props;
    return (
      <>
        {!!visible && (true)}
        {true && <ConditionModal />}
      </>
    );
  }
}

```

**Comment by fanksy** [comment]
Swc4jTranspileOptions options = new Swc4jTranspileOptions()
                .setCaptureAst(true)
                .setMediaType(Swc4jMediaType.Jsx);

**Comment by fanksy** [comment]
Swc4jParseOutput parseOutput = swc4j.parse(script, options);
Swc4jAstModule module = (Swc4jAstModule) parseOutput.getProgram();

**Comment by fanksy** [comment]
com.caoccao.javet.swc4j.exceptions.Swc4jCoreException: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead. at file:///main.js:14:1

  @connect((state) => {
  ~~~~~~~~~~~~~~~~~~~~~

  ~
  ...
  })
  ~~

	at com.caoccao.javet.swc4j.exceptions.Swc4jCoreException.parseError(Swc4jCoreException.java:54)
	at com.caoccao.javet.swc4j.Swc4jNative.coreParse(Native Method)
	at com.caoccao.javet.swc4j.Swc4j.parse(Swc4j.java:80)

**Comment by fanksy** [comment]
I hope this can help you to figure it out.

**Comment by caoccao** [comment]
Please set the media type to `Tsx` and try again.

**Comment by fanksy** [comment]
> Please set the media type to `Tsx` and try again.

测试OK

Tsx完全兼容Jsx ？

Jsx都可以用Tsx来解析？

**Comment by caoccao** [comment]
I think it's your decision to parse the templates as Jsx or Tsx.
