### ISSUE TITLE
[Help] 建议将每个节点的有效行号标记出来

### ISSUE THREAD

**Issue by fanksy** [caoccao/swc4j#4]
深入遍历每个节点将非常耗时，建议在解析语法树阶段将每个节点包含的有效行号（包含嵌套子节点的行号，不包含注释行）标记出来

**Comment by caoccao** [comment]
The info you mentioned is already there.

**Comment by fanksy** [comment]
You could misnuderstand my idea.

Swc4jSpan just contains the first line, if i want to  get other lines in the node, i have to traverse the children of the node.

**Comment by caoccao** [comment]
> You could misunderstand my idea.
> 
> Swc4jSpan just contains the first line, if i want to get other lines in the node, i have to traverse the children of the node.

No, you don't have to. You have the code string, start line number, start position and end position. Just scan the code string and you will get it.

**Comment by fanksy** [comment]
fine, you are right, I must distinguish between multi line comments and single line comments. If you can solve this problem during the parsing ast stage, it will be very convenient.

**Comment by caoccao** [comment]
No. How to calculate that is your responsibility. Not everyone needs that info. So there is no performance overhead wasted on it.
